name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requests
        run: |
          python -m pip install requests
      - name: Update README
        run: |
          python3 update_readme.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
